name: streamlitpy310
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - tensorflow=2.12.0
  - streamlit=1.35.0
  - numpy=1.23.5
  - pillow=9.5.0
  - pip
  - pip:
      - protobuf==4.23.4