name: steel_classifier
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.18
  - streamlit=1.35.0
  - tensorflow=2.15.0
  - numpy=1.24.3
  - pyarrow=14.0.1
  - pillow
  - protobuf>=3.20,<4.0