name: streamlitpy310
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - streamlit=1.35.0
  - numpy=1.24.3
  - pillow=9.5.0
  - pyarrow=14.0.1
  - pip
  - pip:
      - tensorflow==2.15.0
      - protobuf>=3.20,<5.0